# Numpy array basics

In [1]:
import numpy as np

Creating Array from list 

In [2]:
arr_1d = np.array([10, 20, 30, 40, 50])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

print("1D Array:", arr_1d)
print("2D Array:", arr_2d)

1D Array: [10 20 30 40 50]
2D Array: [[1 2 3]
 [4 5 6]]


List vs NumPy array

In [ ]:
py_list = [100, 200, 300, 400, 500] #adds the list or doubles its length
print("Python List Multiplication:", py_list * 2)

np_array = np.array([100, 200, 300, 400, 500]) # multiplies each element by 2
print("NumPy Array Multiplication:", np_array * 2)


Python List Multiplication: [100, 200, 300, 400, 500, 100, 200, 300, 400, 500]
NumPy Array Multiplication: [ 200  400  600  800 1000]


Creating NumPy Array from Scratch

In [6]:
zeros = np.zeros((2, 3))
print("Array of Zeros:\n", zeros)

ones = np.ones((3, 2))
print("Array of Ones:\n", ones) 

full = np.full((2, 4), 7)
print("Array Full of Sevens:\n", full)

random = np.random.rand(2, 3)
print("Array of Random Numbers:\n", random)

sequence = np.arange(0, 10, 2)
print("Sequence Array:", sequence)

Array of Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Array of Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Array Full of Sevens:
 [[7 7 7 7]
 [7 7 7 7]]
Array of Random Numbers:
 [[0.27760443 0.65064739 0.50170215]
 [0.25884098 0.79272107 0.76381999]]
Sequence Array: [0 2 4 6 8]


Vector, Matrix and Tensor

In [7]:
vector = np.array([1, 2, 3])
print("Vector:", vector)

matrix = np.array([[4, 5, 6], [7, 8, 9]])
print("Matrix:\n", matrix)

tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Tensor:\n", tensor)

Vector: [1 2 3]
Matrix:
 [[4 5 6]
 [7 8 9]]
Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array Properties

In [8]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("Shape of array:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Data type of elements:", arr.dtype)
print("Size of each element (in bytes):", arr.itemsize)
print("Total number of elements:", arr.size)

Shape of array: (3, 3)
Number of dimensions: 2
Data type of elements: int64
Size of each element (in bytes): 8
Total number of elements: 9


Array Reshaping

In [12]:
np_arr = np.arange(1, 11)
print("Original Array:", np_arr)

np_arr_reshaped = np_arr.reshape((2, 5))
print("Reshaped Array (2x5):\n", np_arr_reshaped)

np_arr_flattened = np_arr_reshaped.flatten()
print("Flattened Array:", np_arr_flattened)

np_arr_raveled = np_arr_reshaped.ravel()  #Returns a flattened array, but as a view
print("Raveled Array:", np_arr_raveled) 

#Transpose
np_arr_reshaped_transposed = np_arr_reshaped.T
print("Transposed Array:\n", np_arr_reshaped_transposed)

Original Array: [ 1  2  3  4  5  6  7  8  9 10]
Reshaped Array (2x5):
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Flattened Array: [ 1  2  3  4  5  6  7  8  9 10]
Raveled Array: [ 1  2  3  4  5  6  7  8  9 10]
Transposed Array:
 [[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
