NumPy Array Operations 

In [2]:
import numpy as np

In [3]:
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy Array:", np_array)

print("Basic Slicing:", np_array[1:4])  # Slicing from index 1 to 3
print("With Step:", np_array[0:5:2])  # Slicing with step of 2
print("Negative Indices:", np_array[-3:])  # Last three elements


NumPy Array: [10 20 30 40 50]
Basic Slicing: [20 30 40]
With Step: [10 30 50]
Negative Indices: [30 40 50]


In [4]:
np_2darray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D NumPy Array:\n", np_2darray)

print("Specific Elemet:", np_2darray[1, 2])  # Element at 2nd row, 3rd column
print("Entire Row:", np_2darray[0, :])  # First row
print("Entire Column:", np_2darray[:, 1])  # Second column


2D NumPy Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Specific Elemet: 6
Entire Row: [1 2 3]
Entire Column: [2 5 8]


Sorting

In [5]:
np_arr = np.array([3, 5, 1, 2, 4, 6, 8, 7])
print("Original Array:", np_arr)

print("Sorted Array:", np.sort(np_arr))

unsorted_2d = np.array([[3, 5, 1], [2, 4, 6], [9, 8, 7]])
print("Unsorted 2D Array:\n", unsorted_2d)
print("Sorted 2D Array:\n", np.sort(unsorted_2d, axis=1))  # Sort along rows
print("Sorted 2D Array (Columns):\n", np.sort(unsorted_2d, axis=0))  # Sort along columns

Original Array: [3 5 1 2 4 6 8 7]
Sorted Array: [1 2 3 4 5 6 7 8]
Unsorted 2D Array:
 [[3 5 1]
 [2 4 6]
 [9 8 7]]
Sorted 2D Array:
 [[1 3 5]
 [2 4 6]
 [7 8 9]]
Sorted 2D Array (Columns):
 [[2 4 1]
 [3 5 6]
 [9 8 7]]


Filter

In [6]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_numbers = array[array % 2 == 0]
print("Even Numbers:", even_numbers)

#Mask refers to a array where each element indicates whether the condition is met
even_mask = array % 2 == 0
print("Even Number Mask:", array[even_mask])

Even Numbers: [ 2  4  6  8 10]
Even Number Mask: [ 2  4  6  8 10]


Fancy Indexing Vs np.where

In [7]:
where_result = np.where(array > 5)
print(where_result)
print("Indices where elements are greater than 5:", array[where_result])


#Conditonal Selection with np.where
cond_array = np.where(array % 2 == 0, "Even", "Odd")
print("Conditional Selection (Even/Odd):", cond_array)

(array([5, 6, 7, 8, 9]),)
Indices where elements are greater than 5: [ 6  7  8  9 10]
Conditional Selection (Even/Odd): ['Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even']


Adding and Removing data

In [8]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

concatenated = np.concatenate((arr1, arr2))
print("Concatenated Array:", concatenated)

Concatenated Array: [1 2 3 4 5 6]


Array Compatibility

In [9]:
array1 = np.array([[1, 2]])
array2 = np.array([[3, 4]])

print("Compatibility for arrays", array1.shape == array2.shape)

Compatibility for arrays True


In [12]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])
new_row = np.array([[7, 8, 9]])
expanded_array = np.vstack((original_array, new_row))
print("Expanded Array with New Row:\n", expanded_array)

new_column = np.array([[10], [11], [12]])
expanded_array_col = np.hstack((expanded_array, new_column))
print("Expanded Array with New Column:\n", expanded_array_col)

deleted_row_array = np.delete(expanded_array_col, 1, axis=0)
print("Array after Deleting 2nd Row:\n", deleted_row_array)
deleted_col_array = np.delete(deleted_row_array, 2, axis=1)
print("Array after Deleting 3rd Column:\n", deleted_col_array)


Expanded Array with New Row:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Expanded Array with New Column:
 [[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]
Array after Deleting 2nd Row:
 [[ 1  2  3 10]
 [ 7  8  9 12]]
Array after Deleting 3rd Column:
 [[ 1  2 10]
 [ 7  8 12]]
