NumPy Practice 

In [1]:
import numpy as np

In [2]:
#Create numpy array containing numbers 10 to 50
array = np.arange(10, 51)

#Create a 5x5 identity matrix
identity_matrix = np.eye(5)

#Create a 3x4 array filled with value 7
filled_array = np.full((3, 4), 7)

#Create an array of 20 equally spaced numbers between 0 and 1.
equally_spaced_array = np.linspace(0, 1, 20)

print("Array from 10 to 50:\n", array)
print("\n5x5 Identity Matrix:\n", identity_matrix)
print("\n3x4 Array filled with 7:\n", filled_array)
print("\n20 Equally Spaced Numbers between 0 and 1:\n", equally_spaced_array)

Array from 10 to 50:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]

5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

3x4 Array filled with 7:
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]

20 Equally Spaced Numbers between 0 and 1:
 [0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [3]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

#get the shape of the array
print("\nShape of the 2D array:", array_2d.shape)

#get the data type of the array
print("Data type of the 2D array:", array_2d.dtype)     

#get the size of the array
print("Size of the 2D array:", array_2d.size)

#dimensions of the array
print("Number of dimensions of the 2D array:", array_2d.ndim)

#change the daata type of the array to float
array_2d_float = array_2d.astype(float)
print("\n2D array with float data type:\n", array_2d_float)


Shape of the 2D array: (3, 3)
Data type of the 2D array: int64
Size of the 2D array: 9
Number of dimensions of the 2D array: 2

2D array with float data type:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [4]:
#extarct first row from the array
print("\nFirst row of the 2D array:", array_2d[0])

#extract second column from the array
print("Second column of the 2D array:", array_2d[:, 1])

array = np.array([[10,20,30,40,50], 
                  [60,70,80,90,100], 
                  [110,120,130,140,150], 
                  [160,170,180,190,200], 
                  [210,220,230,240,250]])

#extract 3x3 matrix from 5x5 matrix
sub_matrix = array[1:4, 1:4]    
print("\nExtracted 3x3 sub-matrix:\n", sub_matrix)

array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
#reverse the array
print("\nReversed array:", array_1d[::-1])



First row of the 2D array: [1 2 3]
Second column of the 2D array: [2 5 8]

Extracted 3x3 sub-matrix:
 [[ 70  80  90]
 [120 130 140]
 [170 180 190]]

Reversed array: [10  9  8  7  6  5  4  3  2  1]


In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

#add two numpy arrays elemsent-wise
sum_array = np.add(arr1, arr2)
print("\nSum of two arrays:\n", sum_array)  

#multiply all elements of an array by 5
multiplied_array = arr1 * 5
print("\nArray after multiplying by 5:\n", multiplied_array)

#find the square and cube of each element in the array
squared_array = np.square(arr1)
cubed_array = np.power(arr1, 3)
print("\nSquared array:\n", squared_array)      
print("\nCubed array:\n", cubed_array)  



Sum of two arrays:
 [[ 8 10 12]
 [14 16 18]]

Array after multiplying by 5:
 [[ 5 10 15]
 [20 25 30]]

Squared array:
 [[ 1  4  9]
 [16 25 36]]

Cubed array:
 [[  1   8  27]
 [ 64 125 216]]
